//+======================================================================
// $Source:  $
//
// Project:   	Tango Device Server
//
// Description:	java source code for the WorkflowExecutor class .
//              This class is a singleton class and implements everything
//              which exists only once for all the  WorkflowExecutor object
//              It inherits from the DeviceClass class.
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-======================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

package WorkflowExecutor;


import java.util.*;

import org.omg.CORBA.*;
import fr.esrf.Tango.*;
import fr.esrf.TangoDs.*;
import fr.esrf.TangoApi.*;

public class WorkflowExecutorClass extends DeviceClass implements TangoConst
{
	/**
	 *	WorkflowExecutorClass class instance (it is a singleton).
	 */
	private static WorkflowExecutorClass	_instance = null;

	/**
	 *	Class properties array.
	 */
	private DbDatum[]	cl_prop = null;

	//--------- Start of properties data members ----------


//--------- End of properties data members ----------


//===================================================================			
//
// method : 		instance()
// 
// description : 	static method to retrieve the WorkflowExecutorClass object 
//					once it has been initialised
//
//===================================================================			
	public static WorkflowExecutorClass instance()
	{
		if (_instance == null)
		{
			System.err.println("WorkflowExecutorClass is not initialised !!!");
			System.err.println("Exiting");
			System.exit(-1);
		}
		return _instance;
	}

//===================================================================			
//
// method : 		Init()
// 
// description : 	static method to create/retrieve the WorkflowExecutorClass
//					object. This method is the only one which enables a 
//					user to create the object
//
// in :			- class_name : The class name
//
//===================================================================			
	public static WorkflowExecutorClass init(String class_name) throws DevFailed
	{
		if (_instance == null)
		{
			_instance = new WorkflowExecutorClass(class_name);
		}
		return _instance;
	}
	
//===================================================================			
//
// method : 		WorkflowExecutorClass()
// 
// description : 	constructor for the WorkflowExecutorClass class
//
// argument : in : 	- name : The class name
//
//===================================================================			
	protected WorkflowExecutorClass(String name) throws DevFailed
	{
		super(name);

		Util.out2.println("Entering WorkflowExecutorClass constructor");
		write_class_property();
		get_class_property();
	
		Util.out2.println("Leaving WorkflowExecutorClass constructor");
	}
	
//===================================================================			
//
// method : 		command_factory()
// 
// description : 	Create the command object(s) and store them in the
//					command list
//===================================================================			
	public void command_factory()
	{
		command_list.addElement(new StartClass("Start",
			Tango_DEVVAR_STRINGARRAY, Tango_DEV_VOID,
			"Key - value pairs, first name of workflow then initial variables",
			"",
			DispLevel.OPERATOR));
		command_list.addElement(new AbortClass("Abort",
			Tango_DEV_VOID, Tango_DEV_VOID,
			"",
			"",
			DispLevel.OPERATOR));
		command_list.addElement(new PauseClass("Pause",
			Tango_DEV_VOID, Tango_DEV_VOID,
			"",
			"",
			DispLevel.OPERATOR));
		command_list.addElement(new ResumeClass("Resume",
			Tango_DEV_VOID, Tango_DEV_VOID,
			"",
			"",
			DispLevel.OPERATOR));
		command_list.addElement(new GetReviewDataClass("GetReviewData",
			Tango_DEV_VOID, Tango_DEV_STRING,
			"",
			"XML string describing the expected review input and its current values",
			DispLevel.OPERATOR));
		command_list.addElement(new GetScalarValuesMapClass("GetScalarValuesMap",
			Tango_DEV_VOID, Tango_DEVVAR_STRINGARRAY,
			"",
			"The review data as key/value pairs",
			DispLevel.OPERATOR));
		command_list.addElement(new SetScalarValuesMapClass("SetScalarValuesMap",
			Tango_DEVVAR_STRINGARRAY, Tango_DEV_VOID,
			"Set value for the review data",
			"",
			DispLevel.OPERATOR));
		command_list.addElement(new GetAvailableWorkflowsClass("GetAvailableWorkflows",
			Tango_DEV_VOID, Tango_DEV_STRING,
			"",
			"XML string of available workflows",
			DispLevel.OPERATOR));
		command_list.addElement(new IsDialogClass("IsDialog",
			Tango_DEV_VOID, Tango_DEV_BOOLEAN,
			"",
			"Boolean for dialog",
			DispLevel.OPERATOR));
		command_list.addElement(new SetTangoSpecMockModeCmd("SetTangoSpecMockMode",
			Tango_DEV_BOOLEAN, Tango_DEV_VOID,
			"setTangoSpecMockMode",
			"",
			DispLevel.OPERATOR));
		command_list.addElement(new IsTangoSpecMockModeClass("IsTangoSpecMockMode",
			Tango_DEV_VOID, Tango_DEV_BOOLEAN,
			"",
			"",
			DispLevel.OPERATOR));
		command_list.addElement(new GetWorkflowLogClass("GetWorkflowLog",
			Tango_DEV_VOID, Tango_DEV_STRING,
			"",
			"Total log of the current workflow",
			DispLevel.OPERATOR));
		command_list.addElement(new GetWorkflowLogIncrementalClass("GetWorkflowLogIncremental",
			Tango_DEV_VOID, Tango_DEV_STRING,
			"",
			"Incremental log of the current workflow ",
			DispLevel.OPERATOR));

		//	add polling if any
		for (int i=0 ; i<command_list.size(); i++)
		{
			Command	cmd = (Command)command_list.elementAt(i);
		}
	}


//===================================================================			
//
// method : 		device_factory()
// 
// description : 	Create the device object(s) and store them in the 
//					device list
//
// argument : in : 	String[] devlist : The device name list
//
//===================================================================			
	public void device_factory(String[] devlist) throws DevFailed
	{
	
		for (int i=0 ; i<devlist.length ; i++)
		{
			Util.out4.println("Device name : " + devlist[i]);
						
			// Create device and add it into the device list
			//----------------------------------------------
			device_list.addElement(new WorkflowExecutor(this, devlist[i]));

			// Export device to the outside world
			//----------------------------------------------
			if (Util._UseDb == true)
				export_device(((DeviceImpl)(device_list.elementAt(i))));
			else
				export_device(((DeviceImpl)(device_list.elementAt(i))), devlist[i]);
		}
	}

//=============================================================================
//
//	Method:	attribute_factory(Vector att_list)
//
//=============================================================================
	public void attribute_factory(Vector att_list) throws DevFailed
	{
		//	Attribute : StateAttribute
		Attr	state_attribute = 
			new Attr("StateAttribute", Tango_DEV_STATE, AttrWriteType.READ);
		att_list.addElement(state_attribute);

		//	Attribute : RunningActorName
		Attr	running_actor_name = 
			new Attr("RunningActorName", Tango_DEV_STRING, AttrWriteType.READ);
		att_list.addElement(running_actor_name);

	}

//===================================================================
/**
 *	Get the class property for specified name.
 *
 *	@param name The property name.
 */
//===================================================================
	public DbDatum get_class_property(String name)
	{
		for (int i=0 ; i<cl_prop.length ; i++)
			if (cl_prop[i].name.equals(name))
				return cl_prop[i];
		//	if not found, return  an empty DbDatum
		return new DbDatum(name);
	}

//===================================================================
/**
 *	Read the class properties from database.
 */
//===================================================================			
	public void get_class_property() throws DevFailed
	{
		//	Initialize your default values here.
		//------------------------------------------


		//	Read class properties from database.(Automatic code generation)
		//-------------------------------------------------------------
		if (Util._UseDb==false)
			return;
		String[]	propnames = {
			};

		//	Call database and extract values
		//--------------------------------------------
		cl_prop = get_db_class().get_property(propnames);
		int	i = -1;

		//	End of Automatic code generation
		//-------------------------------------------------------------

	}

//===================================================================
/**
 *	Set class description as property in database
 */
//===================================================================			
	private void write_class_property() throws DevFailed
	{	
		//	First time, check if database used
		//--------------------------------------------
		if (Util._UseDb == false)
			return;

		//	Prepeare DbDatum
		//--------------------------------------------
		DbDatum[]	data = new DbDatum[2];
		data[0] = new DbDatum("ProjectTitle");
		data[0].insert("Tango Device Server");

		data[1] = new DbDatum("Description");
		data[1].insert("This class will encapsulate the DAWB workflow executor");

		//	Call database and and values
		//--------------------------------------------
		get_db_class().put_property(data);
	}

}
